[package]
name = "nass"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
num_enum = "0.7.0"
js-sys = "0.3.61"
bitflags = "2.4.1"
wasm-bindgen = "0.2.63"
cfg-if = "1.0.0"
wee_alloc = { version = "0.4.5", optional = true }
console_error_panic_hook = { version = "0.1.1", optional = true }

[dev-dependencies]
wasm-bindgen-test = "0.3.13"

[features]
# default = ["console_error_panic_hook", "wee_alloc"]
default = ["wee_alloc"]

[profile.release]
# Tell `rustc` to optimize for small code size.
# opt-level = "s"
lto = true
