[package]
name = "nass"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
num_enum = "0.7.0"
js-sys = "0.3.61"
bitflags = "2.4.1"
wasm-bindgen = "0.2.63"
# wasm-opt = "0.116.0"

[dev-dependencies]
wasm-bindgen-test = "0.3.13"

# [profile.release]
# # Tell `rustc` to optimize for small code size.
# opt-level = "s"

# [package.metadata.wasm-pack.profile.release]
# wasm-opt = true
